/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.hack.project;

/**
 *
 * @author panbe
 */
public class PanelDecoration extends javax.swing.JPanel {

    /**
     * Creates new form PanelDecoration
     */
    public PanelDecoration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        labelExit = new javax.swing.JLabel();
        labelMini = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 210, 117));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 42)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(91, 91, 91));
        jLabel4.setText("HackQC18");

        labelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/hack/project/cancel.png"))); // NOI18N
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelExitMouseExited(evt);
            }
        });

        labelMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/hack/project/mini.png"))); // NOI18N
        labelMini.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                labelMiniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                labelMiniFocusLost(evt);
            }
        });
        labelMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMiniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1152, Short.MAX_VALUE)
                .addComponent(labelMini)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelExit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(labelMini)
            .addComponent(labelExit)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelMiniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_labelMiniFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_labelMiniFocusGained

    private void labelMiniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_labelMiniFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_labelMiniFocusLost

    private void labelMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelMiniMouseClicked

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelExitMouseClicked

    private void labelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelExitMouseEntered

    private void labelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelExitMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelMini;
    // End of variables declaration//GEN-END:variables
}
